repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-shebang-scripts-are-executable
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: detect-aws-credentials
    args:
    - --allow-missing-credentials
  - id: detect-private-key
  - id: destroyed-symlinks
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/hugoh/pre-commit-fish.git
  rev: v1.2
  hooks:
  - id: fish_syntax
  - id: fish_indent
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.8.0.4
  hooks:
  - id: shellcheck
    exclude: ^config/git/template/hooks/pre-commit
